# Generated by Django 4.2.11 on 2024-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_rename_first_name_customer_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
