# Generated by Django 4.2.11 on 2024-05-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
