# Generated by Django 4.2.11 on 2024-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_photo_customer_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
