# Generated by Django 4.2.11 on 2024-05-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_alter_customer_user_alter_photo_customer_annotation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotation',
            new_name='tobeAnnotated',
        ),
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.photo')),
            ],
        ),
    ]
