# Generated by Django 4.2.11 on 2024-05-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_objects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
