# Generated by Django 4.2.11 on 2024-05-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_photo_image_objects_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedimage',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='annotatedimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotatedimage',
            name='start_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotatedimage',
            name='start_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotatedimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
