# Generated by Django 4.2.11 on 2024-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_remove_annotatedimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedimage',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated_images'),
        ),
    ]
