# Generated by Django 4.2.11 on 2024-05-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_annotatedimage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedimage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.customer'),
        ),
    ]
