# Generated by Django 4.2.11 on 2024-05-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_annotatedimage_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_request',
            new_name='jobRequest',
        ),
        migrations.AddField(
            model_name='photo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
