# Generated by Django 4.2.11 on 2024-05-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_rename_job_request_jobrequest_photo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_objects',
            field=models.CharField(blank=True, default=list, max_length=255),
        ),
        migrations.CreateModel(
            name='imageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.photo')),
            ],
        ),
    ]
