# Generated by Django 4.2.11 on 2024-05-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0024_alter_photo_image_objects_imageobject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imageObject',
            new_name='Object',
        ),
    ]
