# Generated by Django 4.2.11 on 2024-05-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_rename_imageobject_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_objects',
        ),
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.photo'),
        ),
    ]
